### PR TITLE
Change named from pysyft_proto to syft_proto

### PR DESCRIPTION
**Pull request by iamtrask**
Since the spec is not specific to the python implementation of Syft, it should not be called PySyft-Proto, but rather Syft-Proto

### CODE REVIEW

**Comment by vvmnnnkv** [comment]
@iamtrask do we need `syft_proto/proto.json` file?
The should be only one :)

**Comment by karlhigley** [comment]
Yeah, the old `proto.json` should probably be deleted unless there's some reason to keep it around.

**Comment by vvmnnnkv** [comment]
Initially `proto.json` file in the root was meant to be single source of truth and used by both python and js packages (and maybe other packages added later. E.g. Kotlin?)

**Comment by iamtrask** [comment]
Your call. I assumed it was a polyglot thing.

**Comment by karlhigley** [comment]
I had that backwards, I think the one in the root should stay and the new one should be removed. setup.py [copies the JSON file from root](https://github.com/OpenMined/proto/blob/master/setup.py#L6-L8) to include it in the package.

**Comment by iamtrask** [comment]
Sounds good to me. I did notice that part. Don't forget to remove it from
the data_dependencies as well

**Pull request merged**
